### ISSUE TITLE
Add an executable with CLI options to use the library on a CSV file

### ISSUE THREAD

**Issue by harendra-kumar** [composewell/bench-show#1]
`bench-show` is currently only a library to parse the benchmark output CSV file and show the results. Along with the library APIs, it would be nice to have a convenient executable with command line options corresponding to the Config API to generate graphs and reports from a csv file, as requested, without writing a program. From the command line we can choose the type of the report (text or graph), the output file, the format of the report, the comparison strategy etc.

**Comment by harendra-kumar** [comment]
http://hackage.haskell.org/package/optparse-simple or http://hackage.haskell.org/package/optparse-applicative can be used for options parsing and we just need to covert the options to config options and run the benchmark showing functions with the config.

**Comment by SanchayanMaity** [comment]
@harendra-kumar If you have not assigned this to anyone else, I would like to work on this.

**Comment by harendra-kumar** [comment]
@SanchayanMaity go for it. Let me know if you need any info or help.

**Comment by SanchayanMaity** [comment]
@harendra-kumar  I am wondering how does one specify optparse-applicative parser for functions in Config? Like for this one selectFields :: [String] -> [String]?

**Comment by harendra-kumar** [comment]
All library options may not map directly to the CLI. Library can be much more powerful than CLI. In fact, we should try to keep the CLI simple to begin with and add more things as needed. 

In this particular case the library can select fields from available fields, however specifying a generic map on CLI is not practical. We can just have something like `--select-fields "time,rss"` and just select those fields in the output which are specified on the command line. If a field name specified on the command line is not available in the file then the resulting error message can show the available fields so that the user knows what to specify. 

It is also possible to implement a CLI option to show all available fields and then the user can specify the ones he/she wants. Therefore, that function you are referring to is implemented in the user's mind, not specified on the CLI :-)

**Comment by harendra-kumar** [comment]
You can also specify the field/benchmark selection as a regex on CLI, but I think we should keep it simple to start with and then add more stuff incrementally. Especially benchmark selection could be useful as regex, because we have may many of those and we may want to filter based on a pattern.

**Comment by harendra-kumar** [comment]
Fixed via #2
